# Generated by Django 4.0 on 2022-09-10 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentuser',
            old_name='pass_word',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='studentuser',
            name='email',
        ),
    ]
