# Generated by Django 4.0 on 2022-09-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_rename_pass_word_studentuser_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='password',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
